### ISSUE TITLE
relabel_epoch and num_epoch

### ISSUE THREAD

**Issue by zzzzzzyang** [1980x/Cocuring#1]
Thanks for your work, I want to know the value of relabel_epoch and num_epoch for RAFDB, Ferplus and Affectnet respectively

**Comment by 1980x** [comment]
Hi. Sorry for late reply. relabel_epoch values are 5,5 , 3  and num_epoch values are 40,40,20 respectively for RAFDB, Ferplus and Affectnet datasets.
